function [ Final,FinalOcc ] = IPHIv1( Frame,occ )
%IPHIV1 此处显示有关此函数的摘要
%   此处显示详细说明
[height,width]=size(Frame);
rows=height/4;
cols=width/4;

vrtP=zeros(4,4);
hrzP=zeros(4,4);
dlP=zeros(4,4);
drP=zeros(4,4);

Frame=double(Frame);
% vrtR=0;
% hrzR=0;
% dlR=0;
% drR;
% 
% curPixW=zeros(4,4);
% curOccW=zeros(4,4);


for i=2:rows-1
    for j=2:cols-1%跳过边缘
        if (sum(sum(occ((i-1)*4+1:i*4,(j-1)*4+1:j*4)))~=16)%如果当前块有空洞
            
            curPixW=Frame((i-1)*4+1:i*4,(j-1)*4+1:j*4);
            curOccW=occ((i-1)*4+1:i*4,(j-1)*4+1:j*4);
            
            vrtP(:,1)=deal(Frame((i-1)*4,(j-1)*4+1));
            vrtP(:,2)=deal(Frame((i-1)*4,(j-1)*4+2));
            vrtP(:,3)=deal(Frame((i-1)*4,(j-1)*4+3));
            vrtP(:,4)=deal(Frame((i-1)*4,(j-1)*4+4));
            vrtR=sum(sum((vrtP(curOccW==1)-curPixW(curOccW==1))));
            %垂直
            hrzP(1,:)=deal(Frame((i-1)*4+1,(j-1)*4));
            hrzP(2,:)=deal(Frame((i-1)*4+2,(j-1)*4));
            hrzP(3,:)=deal(Frame((i-1)*4+3,(j-1)*4));
            hrzP(4,:)=deal(Frame((i-1)*4+4,(j-1)*4));
            hrzR=sum(sum((hrzP(curOccW==1)-curPixW(curOccW==1))));
            %水平
            dlP(1,1)=(Frame((i-1)*4,(j-1)*4+1)+2*Frame((i-1)*4,(j-1)*4+2)+Frame((i-1)*4,(j-1)*4+3)+2)/4;
            [dlP(1,2),dlP(2,1)]=deal((Frame((i-1)*4,(j-1)*4+2)+2*Frame((i-1)*4,(j-1)*4+3)+...
                Frame((i-1)*4,(j-1)*4+4)+2)/4);
            [dlP(1,3),dlP(2,2),dlP(3,1)]=deal((Frame((i-1)*4,(j-1)*4+3)+2*Frame((i-1)*4,(j-1)*4+4)+...
                Frame((i-1)*4,(j-1)*4+5)+2)/4);
            [dlP(1,4),dlP(2,3),dlP(3,2),dlP(4,1)]=deal((Frame((i-1)*4,(j-1)*4+4)+2*Frame((i-1)*4,(j-1)*4+5)+...
                Frame((i-1)*4,(j-1)*4+6)+2)/4);
            [dlP(2,4),dlP(3,3),dlP(4,2)]=deal((Frame((i-1)*4,(j-1)*4+5)+2*Frame((i-1)*4,(j-1)*4+6)+...
                Frame((i-1)*4,(j-1)*4+7)+2)/4);
            [dlP(3,4),dlP(4,3)]=deal((Frame((i-1)*4,(j-1)*4+6)+2*Frame((i-1)*4,(j-1)*4+7)+...
                Frame((i-1)*4,(j-1)*4+8)+2)/4);
            dlP(4,4)=(Frame((i-1)*4,(j-1)*4+7)+3*Frame((i-1)*4,(j-1)*4+8)+2)/4;
            dlR=sum(sum((dlP(curOccW==1)-curPixW(curOccW==1))));
            %左下
            drP(1,4)=dlP(1,2);
            [drP(1,3),drP(2,4)]=deal(dlP(1,1));
            [drP(1,2),drP(2,3),drP(3,4)]=deal((Frame((i-1)*4,(j-1)*4)+2*Frame((i-1)*4,(j-1)*4+1)+...
                Frame((i-1)*4,(j-1)*4+2)+2)/4);
            [drP(1,1),drP(2,2),drP(3,3),drP(4,4)]=deal((2*Frame((i-1)*4,(j-1)*4)+Frame((i-1)*4,(j-1)*4+1)+...
                Frame((i-1)*4+1,(j-1)*4)+2)/4);
            [drP(2,1),drP(3,2),drP(4,3)]=deal((Frame((i-1)*4,(j-1)*4)+Frame((i-1)*4+2,(j-1)*4)+...
                2*Frame((i-1)*4+1,(j-1)*4)+2)/4);
            [drP(3,1),drP(4,2)]=deal((Frame((i-1)*4+1,(j-1)*4)+Frame((i-1)*4+3,(j-1)*4)+...
                2*Frame((i-1)*4+2,(j-1)*4)+2)/4);
            drP(4,1)=(Frame((i-1)*4+2,(j-1)*4)+Frame((i-1)*4+4,(j-1)*4)+2*Frame((i-1)*4+3,(j-1)*4)+2)/4;
            drR=sum(sum((drP(curOccW==1)-curPixW(curOccW==1))));
            %右下
            [~,DIR]=min([vrtR,hrzR,dlR,drR]);
            [r,c]=find(occ((i-1)*4+1:i*4,(j-1)*4+1:j*4)==0);
            r=r+(i-1)*4;
            c=c+(j-1)*4;
            if (DIR==1)
                for m=1:size(r)
                    Frame(r(m),c(m))=(occ(r(m),c(m)-1)*Frame(r(m),c(m)-1)+...
                        occ(r(m),c(m)+1)*Frame(r(m),c(m)+1)+...
                        occ(r(m)-1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        4*occ(r(m)-1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)-1,c(m)+1)*Frame(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        4*occ(r(m)+1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)+1,c(m)+1)*Frame(r(m)-1,c(m)+1))/...
                        (occ(r(m),c(m)-1)+(occ(r(m),c(m)+1))+...
                        occ(r(m)-1,c(m)-1)+4*occ(r(m)-1,c(m))+occ(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)+4*occ(r(m)+1,c(m))+occ(r(m)+1,c(m)+1));
                    occ(r(m),c(m))=1;
                end
            elseif(DIR==2)
                for m=1:size(r)
                    Frame(r(m),c(m))=(4*occ(r(m),c(m)-1)*Frame(r(m),c(m)-1)+...
                        4*occ(r(m),c(m)+1)*Frame(r(m),c(m)+1)+...
                        occ(r(m)-1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)-1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)-1,c(m)+1)*Frame(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)+1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)+1,c(m)+1)*Frame(r(m)-1,c(m)+1))/...
                        (4*occ(r(m),c(m)-1)+(4*occ(r(m),c(m)+1))+...
                        occ(r(m)-1,c(m)-1)+occ(r(m)-1,c(m))+occ(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)+occ(r(m)+1,c(m))+occ(r(m)+1,c(m)+1));
                    occ(r(m),c(m))=1;
                end
            elseif(DIR==3)
                for m=1:size(r)
                    Frame(r(m),c(m))=(occ(r(m),c(m)-1)*Frame(r(m),c(m)-1)+...
                        occ(r(m),c(m)+1)*Frame(r(m),c(m)+1)+...
                        occ(r(m)-1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)-1,c(m))*Frame(r(m)-1,c(m))+...
                        4*occ(r(m)-1,c(m)+1)*Frame(r(m)-1,c(m)+1)+...
                        4*occ(r(m)+1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)+1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)+1,c(m)+1)*Frame(r(m)-1,c(m)+1))/...
                        (occ(r(m),c(m)-1)+(occ(r(m),c(m)+1))+...
                        occ(r(m)-1,c(m)-1)+occ(r(m)-1,c(m))+4*occ(r(m)-1,c(m)+1)+...
                        4*occ(r(m)+1,c(m)-1)+occ(r(m)+1,c(m))+occ(r(m)+1,c(m)+1));
                    occ(r(m),c(m))=1;
                end
            elseif(DIR==4)
                for m=1:size(r)
                    Frame(r(m),c(m))=(occ(r(m),c(m)-1)*Frame(r(m),c(m)-1)+...
                        occ(r(m),c(m)+1)*Frame(r(m),c(m)+1)+...
                        4*occ(r(m)-1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)-1,c(m))*Frame(r(m)-1,c(m))+...
                        occ(r(m)-1,c(m)+1)*Frame(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)*Frame(r(m)-1,c(m)-1)+...
                        occ(r(m)+1,c(m))*Frame(r(m)-1,c(m))+...
                        4*occ(r(m)+1,c(m)+1)*Frame(r(m)-1,c(m)+1))/...
                        (occ(r(m),c(m)-1)+(occ(r(m),c(m)+1))+...
                        4*occ(r(m)-1,c(m)-1)+occ(r(m)-1,c(m))+occ(r(m)-1,c(m)+1)+...
                        occ(r(m)+1,c(m)-1)+occ(r(m)+1,c(m))+4*occ(r(m)+1,c(m)+1));
                    occ(r(m),c(m))=1;
                end
            end
        end
    end
end
FinalOcc=occ;
Final=uint8(Frame);
end
        
